services:
  api:
    build: ./class-management-api
    command: sh -c 'sleep 7 ; npm start'
    depends_on:
      - db
    ports:
      - 8080:8080
  client:
    build: ./class-management-client
    command: sh -c 'sleep 9 ; npm start'
    ports:
      - 3000:3000
    depends_on:
      - api
  db:
    build: ./class-management-db
    command: mysqld --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: "classmanage"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3307:3306