import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Class Management Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The CM Center!
        </h1>

        <p className={styles.description}>
          Get started by selecting your user type.
        </p>

        <div className={styles.grid}>
          <Link href="/student/Auth" className={styles.card}>
            <h2>Student &rarr;</h2>
            <p>View your classes and grades in the CM Student Center</p>
          </Link>

          <Link href="/teacher/Auth" className={styles.card}>
            <h2>Teacher &rarr;</h2>
            <p>Manage your classes and grades in the CM Teacher Center</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
